export const PREDEFINED_LOCATIONS = [
  "Volkswagen T7",
  "Toyota T7",
  "RAM Castelo Branco",
  "Marketing Galpão",
  "Compliance",
  "Primeira Mão T7",
  "Primeira Mão Off Road T7",
  "BYD Marista",
  "Tudo Chevrolet Mutirão",
  "Nissan 85",
  "Primeira Mão 85",
  "BMW Carros",
  "CRT",
  "Jeep / RAM BR",
  "Triumph",
  "BMW Motos",
  "Seminovos Motos",
  "Tudo Chevrolet Buriti",
  "Toyota Buriti",
  "Primeira Mão Buriti",
  "Hyundai T9",
  "Jeep T9",
  "BYD Cidade Jardim",
  "Hyundai Cidade Jardim",
  "Primeira Mão Cidade Jardim",
  "Outlet Shopping",
  "Primeira Mão Shopping",
  "Toyota Anapolis",
  "Hyundai Anapolis",
  "Primeira Mão Anapolis",
  "Jeep / RAM Anapolis",
  "Nissan Anapolis",
  "Fazendinha",
  "Primeira Mão Galpão",
  "Primeira Mão Digital Galpão",
  "Corretora",
  "Seguros",
  "CSC",
  "DP",
  "Contabilidade",
  "Controladoria",
  "Administrativo",
  "Diretoria",
  "Auditoria Galpão",
  "Compras Galpão",
  "RH Galpão",
  "Compras CRT",
  "CRT Galpão",
  "Marketing BYD",
  "CRM T.I",
  "Compliance Galpão"
];
